PROMPT == INSERTING into SV_FWK_CSS_DATA

--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (1,10,'.apexir_WORKSHEET_DATA th.current','background: url($PATH$svFWKsReportBG-Dark-Hover.png) 0 0 repeat-x;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (2,20,'#logo-and-tabs','background: url($PATH$svFWKtopBackground.png) 0 0 no-repeat #b0b0b0;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (3,30,'button.apexir-button','background: url($PATH$svFWKsIRButtons.png) 100% -50px no-repeat;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (4,40,'button.apexir-button span','background: url($PATH$svFWKsIRButtons.png) 0 0 no-repeat;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (5,50,'button.apexir-go-button','background: url($PATH$svFWKsIRButtons.png) 100% -200px no-repeat;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (6,60,'button.apexir-go-button span','background: url($PATH$svFWKsIRButtons.png) 0 -150px no-repeat;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (7,70,'#apexir_TOOLBAR button.dhtmlMenu','background: url($PATH$svFWKsIRButtons.png) 100% -100px no-repeat;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (8,80,'#apexir_TOOLBAR button.dhtmlMenu span','background: url($PATH$svFWKsIRButtons.png) 0 0 no-repeat;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (9,90,'#apexir_TOOLBAR button.dhtmlMenuOn','background: url($PATH$svFWKsIRButtons.png) 100% -100px no-repeat;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (10,100,'#apexir_TOOLBAR button.dhtmlMenuOn span','background: url($PATH$svFWKsIRButtons.png) 0 0 no-repeat;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (11,110,'div.apexir_COLUMN_SELECTOR a.apexir_SEARCHICON','background: url($PATH$svFWKsIRButtons.png) 0 -250px no-repeat;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (12,120,'#tab-holder','background: url($PATH$svFWKtabBackground.png) 0 0 no-repeat #555555; ','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (13,130,'#region-tabs','background: url($PATH$svFWKsubTabBackground.png) repeat-x #ddd;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (14,140,'.formRegionHeader, .exceptionRegionHeader','background: url($PATH$svFWKformHeaderBackground.png) no-repeat scroll 0 0 #254A5C;height: 30px;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (15,150,'button.button-default','background: transparent url($PATH$svFWKsButtons.png) no-repeat right -49px;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (16,160,'button.button-default span','background: transparent url($PATH$svFWKsButtons.png) no-repeat left 0;','Y');
--Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (17,170,'@media screen and (-webkit-min-device-pixel-ratio:0) {  ','{background: transparent url($PATH$svFWKsButtons.png) no-repeat right -50px;}','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,180,'.apexir_WORKSHEET_DATA th','background-image: url($PATH$tabBackground.png);background-repeat:repeat-x;background-color: #727272;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,190,'.apexir_WORKSHEET_DATA th.current','background: url($PATH$sReportBG-Dark-Hover.png) 0 0 repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,200,'button.apexir-button','background: url($PATH$sIRButton.png) 100% -50px no-repeat;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,210,'button.apexir-button span','background: url($PATH$sIRButton.png) 0 0 no-repeat;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,220,'button.apexir-go-button','background: url($PATH$sIRButton.png) 100% -200px no-repeat;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,230,'button.apexir-go-button span','background: url($PATH$sIRButton.png) 0 -150px no-repeat;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,240,'#apexir_TOOLBAR button.dhtmlMenu','background: url($PATH$sIRButton.png) 100% -100px no-repeat;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,250,'#apexir_TOOLBAR button.dhtmlMenu span','background: url($PATH$sIRButton.png) 0 0 no-repeat;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,260,'#apexir_TOOLBAR button.dhtmlMenuOn','background: url($PATH$sIRButton.png) 100% -100px no-repeat;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,270,'#apexir_TOOLBAR button.dhtmlMenuOn span','background: url($PATH$sIRButton.png) 0 0 no-repeat;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,280,'div.apexir_COLUMN_SELECTOR a.apexir_SEARCHICON','background: url($PATH$sIRButton.png) 0 -250px no-repeat;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,290,'#success_message','background: url($PATH$sReportBG.png) 0 -200px #DADADA repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,300,'#notification_message','background: url($PATH$sReportBG.png) 0 -200px #DADADA repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,310,'#tabs','background-image: url($PATH$tabBackground.png); ','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,320,'#region-tabs','background: url($PATH$subTabBackground.png) repeat-x #ddd;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,330,'#left-sidebar','background: url($PATH$sidebarBackground.png) repeat-x #c5c4c3;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,340,'th.reportHeader','background: url($PATH$tabBackground.png) #768896 repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,350,'.tabTD, .tabTable td','background-image: url($PATH$subTabBackground.png);background-repeat:repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,360,'.tabTable td.currentTab','background-image: url($PATH$formHeaderBackground.png);background-repeat:repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,370,'.sidebar','background: #c5c3c3;background-image: url($PATH$sidebarBackground.png);background-repeat:repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,380,'.formRegionHeader, .exceptionRegionHeader','background: url($PATH$formRegionTitleBackground.png) repeat-x scroll 0 0 #6f8c9b;height: 30px;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,390,'.verticalReport th','background-image: url($PATH$formHeaderBackground.png);background-repeat:repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,400,'.parentTabTable td','background-image: url($PATH$tabBackground.png);background-repeat:repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,410,'.parentTabTable td.currentParentTab','background-image: url($PATH$formHeaderBackground.png);background-repeat:repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,420,'.reportHeader','background-image: url($PATH$formHeaderBackground.png);background-repeat:repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,430,'.tab','background-image: url($PATH$subTabBackground.png);background-repeat:repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,440,'button.button-default','background: transparent url($PATH$sButtons.png) no-repeat right -49px;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,450,'@media screen and (-webkit-min-device-pixel-ratio:0) { button.button-default','background: transparent url($PATH$sButtons.png) no-repeat right -50px;}','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,460,'button.button-default span','background: transparent url($PATH$sButtons.png) no-repeat left 0;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,470,'div.error_container div.sErrorText','background: url($PATH$sErrorIcon.png) 0 5px no-repeat;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,480,'ul.dropdown li.hover,ul.dropdown li:hover','background-color: #697888;background-image: url($PATH$tabCurrentBackground.png); ','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,490,'ul#tabs li.first-current, li.current','background-color: #768896;background-image: url($PATH$formRegionTitleBackground.png); ','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,500,'ul.dropdown li .currentTab ','background-color: #697888;background-image: url($PATH$tabCurrentBackground.png); ','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,510,'ul.dropdown li','background-image: url($PATH$subTabBackground.png);background-repeat:repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,520,'ul.dropdown ul li','background-image: none;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,530,'ul#region-tabs li.rt-current','background: url($PATH$formRegionTitleBackground.png) #768896 repeat-x;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,540,'#hidePanel','background: url($PATH$sidebarHide.png) no-repeat;background-color: #bbb;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,550,'#showPanel','background: url($PATH$sidebarShow.png) no-repeat;background-color: #bbb;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,560,'.ui-progressbar-value','background-image: url($PATH$pbar-ani.gif);','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,570,'.ui-widget-header','background: url("$PATH$formRegionTitleBackground.png") repeat-x scroll 0 0 #6F8C9B;border: 1px solid #AAAAAA;color: #FFF;font-weight: bold;','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,580,'.ui-widget-header .ui-icon','background-image: url("$PATH$CLOSE.png");','Y');
Insert into SV_SEC_CSS (CSS_ID,SEQ,CLASS_NAME,CONTENTS,ACTIVE_FLAG) values (NULL,590,'ui-icon-closethick','background-position: 0px 0px;','Y');

COMMIT;