--  VERSION @SV_VERSION@
--
--    NAME
--      _install_app.sql
--
--    DESCRIPTION
--      Shell Script used to install the eFramework APEX applications
--
--    NOTES
--      Assumes the SYS user is connected.
--
--    Arguments:
--      ^1 = app_file
--      ^2 = app_id
--
--    MODIFIED   (MM/DD/YYYY)
--      tsthilaire   16-FEB-2014  - Created   
--
--

--  feedback - Displays the number of records returned by a script ON=1
set feedback off
--  termout - display of output generated by commands in a script that is executed
set termout on
-- serverout - allow dbms_output.put_line
set serverout off
--  define - Sets the character used to prefix substitution variables
set define '^'
--  concat - Sets the character used to terminate a substitution variable ON=.
set concat on
--  verify off prevents the old/new substitution message
set verify off

-- read the script parameters
def script_ws_file ='^1'

PROMPT  =============================================================================
PROMPT  == Web Service File Start
PROMPT  =============================================================================
PROMPT

-- Check if the application ID already exists for SERT
DECLARE
  l_workspace     varchar2(20) := 'SERT';
  l_workspace_id  number;
  l_app_id_check  NUMBER;
BEGIN

-- Get the Workspace Name ID value
SELECT workspace_id
  INTO l_workspace_id
  FROM apex_workspaces
  WHERE workspace = l_workspace;
  
-- Workspace Security
apex_application_install.set_workspace_id( l_workspace_id );
apex_application_install.generate_offset;
  
EXCEPTION WHEN NO_DATA_FOUND then
    dbms_output.put_line('ISSUE: The workspace SERT does not exist at this time.');
    raise VALUE_ERROR;
END;
/

@@^script_ws_file

-- clear installation settings (prevents collisions)
exec APEX_APPLICATION_INSTALL.CLEAR_ALL;

--  define - Sets the character used to prefix substitution variables
set define '^'
PROMPT  =============================================================================
PROMPT  == Application File ^script_app_file Complete
PROMPT  =============================================================================
PROMPT