--  VERSION @SV_VERSION@
--
--    NAME
--      id_prompts.sql
--
--    DESCRIPTION
--      This is intended to only be called if the ID values are being manually set by the user
--      during installation.
--      Substitutions collected here are expected to be used OUTISDE this script
--
--    Arguments:
--      Variable Definitions are expected to be stored / called from the main install script
--
--    MODIFIED   
--      tsthilaire  February 16, 2014 11:11:11 AM EST - New - "Up Front" version   
--

-- terminate script when an error occurs
WHENEVER SQLERROR EXIT
--  feedback - Displays the number of records returned by a script ON=1
set feedback off
--  termout - display of output generated by commands in a script that is executed
set termout on
-- serverout - allow dbms_output.put_line to be seen in sqlplus
set serverout on
--  define - Sets the character used to prefix substitution variables
set define '^'
--  concat - Sets the character used to terminate a substitution variable ON=.
set concat on
--  verify off prevents the old/new substitution message
set verify off


-- Prompt the user for an application ID overide
ACCEPT sert_app_id  CHAR DEFAULT '' PROMPT 'Please enter an Applicaiton ID for the SERT Application [AUTO] :'
ACCEPT sert_mgmt_id CHAR DEFAULT '' PROMPT 'Please enter an Applicaiton ID for the SERT Management Application AUTO] :'


-- VAR = Bind Variables
-- set this flag to 'YES' if the APP script should be run
var app_id_check NUMBER

PROMPT ... Checking Application ID availability...
PROMPT 
-- set a bind variable 
  BEGIN
    for c1 in (
              select 'x'
                from apex_applications 
               where application_id = '^sert_app_id'
                  or application_id = '^sert_mgmt_id'
              ) loop
      dbms_output.put_line('Application ID is already installed.');
      -- bogus statement to force exit
      execute immediate 'Failed prerequisite';
    END LOOP;
    dbms_output.put_line('... Application IDs are available');

  EXCEPTION WHEN OTHERS THEN
      dbms_output.put_line('Application ID conflict - can not recover script....');
      raise;
  END;
/







