@tbl/sv_sec_classifications.sql
@tbl/sv_sec_categories.sql
@tbl/sv_sec_attributes.sql
@tbl/sv_sec_attribute_sets.sql
@tbl/sv_sec_attribute_set_attrs.sql
@tbl/sv_sec_attribute_values.sql
@tbl/sv_sec_version.sql
@tbl/sv_sec_help_text.sql
@tbl/sv_sec_help_inter.sql
@tbl/sv_sec_rule_type.sql
@tbl/sv_sec_rule_source.sql
@tbl/sv_sec_impact.sql
@tbl/sv_sec_apex_links.sql
@tbl/sv_sec_score_collections.sql
@tbl/sv_sec_collection.sql
@tbl/sv_sec_collection_data.sql
@tbl/sv_sec_summary_temp.sql
@tbl/sv_sec_exceptions.sql
@tbl/sv_sec_exceptions_fail.sql
@tbl/sv_sec_notations.sql
@tbl/sv_sec_notations_fail.sql
@tbl/sv_sec_event_types.sql
@tbl/sv_sec_events.sql
@tbl/sv_sec_snippets.sql
@tbl/sv_sec_result_temp.sql
@tbl/sv_sec_html_temp.sql
@tbl/sv_sec_htp_procs.sql
@tbl/sv_sec_applications.sql
@tbl/sv_sec_app_evals.sql
@tbl/sv_sec_col_templates.sql
@tbl/sv_sec_colors.sql
@tbl/sv_sec_pref_defaults.sql
@tbl/sv_sec_attr_rpt_inter.sql
@tbl/sv_sec_attr_rpt_cols.sql
@tbl/sv_sec_app_eval_cls.sql
@tbl/sv_sec_app_eval_cat.sql
@tbl/sv_sec_app_eval_attr.sql
@tbl/sv_sec_pdf_temp.sql
@tbl/sv_sec_script_files.sql
@tbl/sv_sec_cover_page.sql
@tbl/sv_sec_component_sigs.sql
@tbl/sv_sec_scheduled_results.sql
@tbl/sv_sec_sched_evals.sql
@tbl/sv_sec_sched_grp.sql
@tbl/sv_sec_sched_grp_apps.sql
@tbl/sv_sec_sched_lists.sql
@tbl/sv_sec_sched_list_members.sql
@tbl/sv_sec_sched_grp_evals.sql
@tbl/sv_sec_css.sql
@tbl/sv_sec_cookie_sessions.sql
@tbl/sv_sec_user_roles.sql
@tbl/sv_sec_user_notif_prefs.sql
@tbl/sv_sec_rpt_generic_cols.sql
