PROMPT == SV_SEC_CSS

CREATE TABLE  SV_SEC_CSS
   (	
     css_id            NUMBER  NOT NULL ,
     seq               NUMBER,
     class_name        VARCHAR2(255),
     contents          VARCHAR2(4000),
     active_flag       VARCHAR2(1),
	 CONSTRAINT sv_sec_css_pk PRIMARY KEY (css_id) ENABLE
   )
/

CREATE SEQUENCE   SV_SEC_CSS_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/

CREATE OR REPLACE TRIGGER  BI_SV_SEC_CSS
  BEFORE INSERT ON SV_SEC_CSS
  FOR EACH ROW
BEGIN
  IF :NEW.CSS_ID IS NULL THEN
    SELECT SV_SEC_CSS_SEQ.NEXTVAL INTO :NEW.CSS_ID FROM dual;
  END IF;
  :NEW.active_flag := 'Y';
END;
/